# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
jobs:
  build:
    executor: gcp-gcr/default
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: ./build.sh -t ${CIRCLE_TAG/v/''}

orbs:
  gcp-gcr: circleci/gcp-gcr@0.12.0
  gcp-gke: circleci/gcp-gke@1.1.0
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
